title: NCHKT
description: 'A collection of resources, and my thoughts on whatever got me interested.'
social_link: twitter
social_username: nachiketnasa
github_repo: blog
github_username: nachiketnasa
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /blog
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
